# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.multunus.com
title: Multunus
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d %B %Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
#auto: true
root: /
permalink: /:year/:month/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
author_dir: blog/author
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/featured_posts.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html,asides/tumblr.html]
blog_index_asides: [custom/asides/category_list.html]
what_we_do_asides: [custom/asides/what_we_do.html]
why_us_asides: [custom/asides/why_us.html]
careers_asides: [custom/asides/careers.html]
about_asides: [custom/asides/about.html]
contact_us_asides: [custom/asides/contact_us.html]
mobile_apps_asides: [custom/asides/mobile_apps.html]
web_apps_asides: [custom/asides/web_apps.html]
opensource_asides: [custom/asides/opensource.html]
love_asides: [custom/asides/love.html]
# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: multunus
twitter_tweet_count: 5
twitter_show_replies: false
twitter_follow_button: false
twitter_show_follower_count: false
twitter_tweet_button: true

# Tumblr
tumblr_user: multunus
tumblr_post_count: 1

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: multunus
disqus_developer: true
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-5073218-1

# Facebook Like
facebook_like: true

#prose.io settings
prose:
  rooturl: "source"
  metadata:
    "source/_posts": |
        layout: post
        title: "Change Title"
        date: 2013-04-11 02:33
        comments: true
        author:
          - Leena
        categories:
          - All Posts
